/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Color;

/**
 *
 * @author 0068961
 */
public class Cadastro extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bemvindoTxt = new javax.swing.JLabel();
        emailF = new javax.swing.JTextField();
        cadastrarBTN = new javax.swing.JButton();
        senhaF = new javax.swing.JPasswordField();
        senhaF1 = new javax.swing.JPasswordField();
        nomeF = new javax.swing.JTextField();
        membroTxt = new javax.swing.JLabel();
        acessarcontaTxt = new javax.swing.JLabel();
        nomeTxt = new javax.swing.JLabel();
        emailTxt = new javax.swing.JLabel();
        senhaTxt = new javax.swing.JLabel();
        senha1Txt = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(398, 598));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        bemvindoTxt.setBackground(new java.awt.Color(102, 102, 102));
        bemvindoTxt.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        bemvindoTxt.setForeground(new java.awt.Color(102, 102, 102));
        bemvindoTxt.setText("Criar Conta");

        emailF.setBackground(new java.awt.Color(230, 230, 230));
        emailF.setForeground(new java.awt.Color(153, 153, 153));
        emailF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailF.setText("seuemail@gmail.com");
        emailF.setBorder(null);
        emailF.setPreferredSize(new java.awt.Dimension(80, 80));
        emailF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFFocusLost(evt);
            }
        });

        cadastrarBTN.setBackground(new java.awt.Color(230, 230, 230));
        cadastrarBTN.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        cadastrarBTN.setForeground(new java.awt.Color(102, 102, 102));
        cadastrarBTN.setText("Cadastrar");
        cadastrarBTN.setBorder(null);
        cadastrarBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        senhaF.setBackground(new java.awt.Color(230, 230, 230));
        senhaF.setForeground(new java.awt.Color(153, 153, 153));
        senhaF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        senhaF.setText("suasenha");
        senhaF.setBorder(null);
        senhaF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                senhaFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                senhaFFocusLost(evt);
            }
        });
        senhaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaFActionPerformed(evt);
            }
        });

        senhaF1.setBackground(new java.awt.Color(230, 230, 230));
        senhaF1.setForeground(new java.awt.Color(153, 153, 153));
        senhaF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        senhaF1.setText("suasenha");
        senhaF1.setBorder(null);
        senhaF1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                senhaF1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                senhaF1FocusLost(evt);
            }
        });
        senhaF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaF1ActionPerformed(evt);
            }
        });

        nomeF.setBackground(new java.awt.Color(230, 230, 230));
        nomeF.setForeground(new java.awt.Color(153, 153, 153));
        nomeF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomeF.setText("seunome");
        nomeF.setBorder(null);
        nomeF.setPreferredSize(new java.awt.Dimension(80, 80));
        nomeF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeFFocusLost(evt);
            }
        });

        membroTxt.setBackground(new java.awt.Color(153, 153, 153));
        membroTxt.setForeground(new java.awt.Color(153, 153, 153));
        membroTxt.setText("Já é um membro?");

        acessarcontaTxt.setBackground(new java.awt.Color(51, 255, 51));
        acessarcontaTxt.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        acessarcontaTxt.setForeground(new java.awt.Color(51, 255, 51));
        acessarcontaTxt.setText("Acesse sua conta");
        acessarcontaTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acessarcontaTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acessarcontaTxtMouseClicked(evt);
            }
        });

        nomeTxt.setBackground(new java.awt.Color(153, 153, 153));
        nomeTxt.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        nomeTxt.setForeground(new java.awt.Color(153, 153, 153));
        nomeTxt.setText("Nome");

        emailTxt.setBackground(new java.awt.Color(153, 153, 153));
        emailTxt.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        emailTxt.setForeground(new java.awt.Color(153, 153, 153));
        emailTxt.setText("Email");

        senhaTxt.setBackground(new java.awt.Color(153, 153, 153));
        senhaTxt.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        senhaTxt.setForeground(new java.awt.Color(153, 153, 153));
        senhaTxt.setText("Senha");

        senha1Txt.setBackground(new java.awt.Color(153, 153, 153));
        senha1Txt.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        senha1Txt.setForeground(new java.awt.Color(153, 153, 153));
        senha1Txt.setText("Repita sua senha");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(senha1Txt)
                    .addComponent(senhaTxt)
                    .addComponent(emailTxt)
                    .addComponent(nomeTxt)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(membroTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acessarcontaTxt))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nomeF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bemvindoTxt)
                        .addComponent(emailF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(senhaF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                            .addComponent(cadastrarBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(senhaF1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(bemvindoTxt)
                .addGap(26, 26, 26)
                .addComponent(nomeTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(emailTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(senhaTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senhaF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(senha1Txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senhaF1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(cadastrarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(membroTxt)
                    .addComponent(acessarcontaTxt))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        senhaF.setEchoChar((char)0);
        senhaF1.setEchoChar((char)0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void senhaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaFActionPerformed

    private void senhaF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaF1ActionPerformed

    private void acessarcontaTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acessarcontaTxtMouseClicked
        FrameApp.trocaPainel("Login", new Login());
    }//GEN-LAST:event_acessarcontaTxtMouseClicked

    private void nomeFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeFFocusGained
        if(this.nomeF.getText().equals("seunome")){
            this.nomeF.setText("");
            this.nomeF.setForeground(new Color(51,51,51));
        }
    }//GEN-LAST:event_nomeFFocusGained

    private void nomeFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeFFocusLost
        if(this.nomeF.getText().equals("")){
            this.nomeF.setText("seunome");
            this.nomeF.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_nomeFFocusLost

    private void emailFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFFocusGained
        if(this.emailF.getText().equals("seuemail@gmail.com")){
            this.emailF.setText("");
            this.emailF.setForeground(new Color(51,51,51));
        }
    }//GEN-LAST:event_emailFFocusGained

    private void emailFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFFocusLost
        if(this.emailF.getText().equals("")){
            this.emailF.setText("seuemail@gmail.com");
            this.emailF.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_emailFFocusLost

    private void senhaFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhaFFocusGained
        this.senhaF.setEchoChar('*');
        String password = String.valueOf(senhaF.getPassword());
        if(password.toLowerCase().equals("suasenha")){
            this.senhaF.setText("");
            this.senhaF.setForeground(new Color(51,51,51));
        }
    }//GEN-LAST:event_senhaFFocusGained

    private void senhaFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhaFFocusLost
        String password = String.valueOf(senhaF.getPassword());
        if(password.equalsIgnoreCase("")){
        if(password.toLowerCase().equals("")){
            this.senhaF.setText("suasenha");
            this.senhaF.setForeground(new Color(153,153,153));
        }
        }
    }//GEN-LAST:event_senhaFFocusLost

    private void senhaF1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhaF1FocusGained
        this.senhaF1.setEchoChar('*');
        String password = String.valueOf(senhaF1.getPassword());
        if(password.toLowerCase().equals("suasenha")){
            this.senhaF1.setText("");
            this.senhaF1.setForeground(new Color(51,51,51));
        }
    }//GEN-LAST:event_senhaF1FocusGained

    private void senhaF1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhaF1FocusLost
        String password = String.valueOf(senhaF1.getPassword());
        if(password.equalsIgnoreCase("")){
        this.senhaF1.setEchoChar((char)0);        
        if(password.toLowerCase().equals("")){
            this.senhaF1.setText("suasenha");
            this.senhaF1.setForeground(new Color(153,153,153));
        }
        }
    }//GEN-LAST:event_senhaF1FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acessarcontaTxt;
    private javax.swing.JLabel bemvindoTxt;
    private javax.swing.JButton cadastrarBTN;
    private javax.swing.JTextField emailF;
    private javax.swing.JLabel emailTxt;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel membroTxt;
    private javax.swing.JTextField nomeF;
    private javax.swing.JLabel nomeTxt;
    private javax.swing.JLabel senha1Txt;
    private javax.swing.JPasswordField senhaF;
    private javax.swing.JPasswordField senhaF1;
    private javax.swing.JLabel senhaTxt;
    // End of variables declaration//GEN-END:variables
}
