/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author 0068961
 */
public class CadastroMidia extends javax.swing.JPanel {

    /**
     * Creates new form CadastroMidia
     */
    public CadastroMidia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Assistido = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btn_cadastroMidia = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Fnome = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Fdata = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        Fnao = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Fsobre = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        Fsim = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1270, 788));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cadastroMidia.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btn_cadastroMidia.setText("Cadastrar Mídia");
        btn_cadastroMidia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_cadastroMidia.setContentAreaFilled(false);
        btn_cadastroMidia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cadastroMidia.setFocusable(false);
        btn_cadastroMidia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastroMidiaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cadastroMidia, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 620, 250, 30));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1270, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 180));

        Fnome.setBackground(new java.awt.Color(250, 250, 250));
        Fnome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Fnome.setEnabled(false);
        jPanel1.add(Fnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 560, 40));

        jComboBox1.setBackground(new java.awt.Color(250, 250, 250));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L", "10", "12", "14", "16", "18" }));
        jComboBox1.setToolTipText("");
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 110, 40));

        jLabel1.setText("Nome*:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel2.setText("Tipo*");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, -1, -1));

        Fdata.setBackground(new java.awt.Color(250, 250, 250));
        try {
            Fdata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Fdata.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Fdata.setEnabled(false);
        Fdata.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(Fdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 220, 260, 40));

        jLabel3.setText("Data de lançamento:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 200, -1, -1));

        Fnao.setBackground(new java.awt.Color(250, 250, 250));
        Assistido.add(Fnao);
        Fnao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Fnao.setText("Não");
        Fnao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Fnao.setFocusable(false);
        jPanel1.add(Fnao, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 360, 60, 30));

        Fsobre.setBackground(new java.awt.Color(250, 250, 250));
        Fsobre.setColumns(20);
        Fsobre.setRows(5);
        Fsobre.setEnabled(false);
        jScrollPane2.setViewportView(Fsobre);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 560, 320));

        jLabel4.setText("Descrição:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jSlider1.setBackground(new java.awt.Color(250, 250, 250));
        jSlider1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSlider1.setForeground(new java.awt.Color(51, 51, 51));
        jSlider1.setMajorTickSpacing(1);
        jSlider1.setMaximum(5);
        jSlider1.setMinimum(1);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setToolTipText("");
        jPanel1.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 520, 520, 50));

        jLabel5.setText("Avaliação*:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, -1, -1));

        Fsim.setBackground(new java.awt.Color(250, 250, 250));
        Assistido.add(Fsim);
        Fsim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Fsim.setText("Sim");
        Fsim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Fsim.setFocusable(false);
        jPanel1.add(Fsim, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 360, 60, 30));

        jLabel6.setText("Assistido*:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 340, -1, -1));

        jComboBox2.setBackground(new java.awt.Color(250, 250, 250));
        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox2.setMaximumRowCount(3);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filme", "Série", "Livro" }));
        jComboBox2.setToolTipText("");
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 210, 40));

        jLabel8.setText("Classificação:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 790));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastroMidiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastroMidiaActionPerformed
        FrameApp_home.trocaPanel("CadastroMidia", new CadastroMidia());
    }//GEN-LAST:event_btn_cadastroMidiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Assistido;
    private javax.swing.JFormattedTextField Fdata;
    private javax.swing.JRadioButton Fnao;
    private javax.swing.JTextField Fnome;
    private javax.swing.JRadioButton Fsim;
    private javax.swing.JTextArea Fsobre;
    private javax.swing.JButton btn_cadastroMidia;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
