/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import control.MidiaControl;
import control.UsuarioControl;
import java.util.ArrayList;
import java.util.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Midia;
import model.Usuario;

/**
 *
 * @author 0068961
 */
public class CadastroMidia extends javax.swing.JPanel {

    private static MidiaControl midiaControl;
    Usuario userSelecionado;
    private ArrayList<String> generosSelecionados = new ArrayList<>();
    
    public CadastroMidia() {
        midiaControl = new MidiaControl();
        initComponents();
        config();
        
    }
    
    public CadastroMidia(Usuario userSelecionado){
        midiaControl = new MidiaControl();
        this.userSelecionado = userSelecionado;
        initComponents();
        config();
    }
    
    public void config(){
        
        //boolean ok = ListaCategorias();
        //if(ok){
          //  System.out.println("deu certo");
        //} else {
          //  System.err.println("deu erro");
        //}
        
        ImageIcon imgLogo = new ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\resources\\backmidia.png");
        this.backmidia.setIcon(imgLogo);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Assistido = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btn_voltar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        backmidia = new javax.swing.JLabel();
        Fnome = new javax.swing.JTextField();
        nomeTxt = new javax.swing.JLabel();
        tipoTxt = new javax.swing.JLabel();
        Fdata = new javax.swing.JFormattedTextField();
        dataTxt = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Fsobre = new javax.swing.JTextArea();
        descricaoTxt = new javax.swing.JLabel();
        avaliarSlider = new javax.swing.JSlider();
        avaliacaoTxt = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        classificacaoTxt = new javax.swing.JLabel();
        generoTxt = new javax.swing.JLabel();
        Fplataforma = new javax.swing.JTextField();
        plataformaTxt = new javax.swing.JLabel();
        btn_cadastroMidia1 = new javax.swing.JButton();
        comboClassificacao = new javax.swing.JComboBox<>();
        Fcriador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnGeneros = new javax.swing.JButton();
        Fgenero = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1270, 788));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_voltar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_voltar.setContentAreaFilled(false);
        btn_voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_voltar.setFocusable(false);
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 700, 250, 30));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backmidia, javax.swing.GroupLayout.DEFAULT_SIZE, 1270, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backmidia, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 180));

        Fnome.setBackground(new java.awt.Color(250, 250, 250));
        Fnome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(Fnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 560, 40));

        nomeTxt.setText("Nome*:");
        jPanel1.add(nomeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        tipoTxt.setText("Tipo*");
        jPanel1.add(tipoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, -1, -1));

        Fdata.setBackground(new java.awt.Color(250, 250, 250));
        try {
            Fdata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Fdata.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Fdata.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(Fdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 590, 530, 40));

        dataTxt.setText("Data de lançamento:");
        jPanel1.add(dataTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 560, -1, -1));

        Fsobre.setBackground(new java.awt.Color(250, 250, 250));
        Fsobre.setColumns(20);
        Fsobre.setRows(5);
        jScrollPane2.setViewportView(Fsobre);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 560, 320));

        descricaoTxt.setText("Descrição:");
        jPanel1.add(descricaoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        avaliarSlider.setBackground(new java.awt.Color(250, 250, 250));
        avaliarSlider.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        avaliarSlider.setForeground(new java.awt.Color(51, 51, 51));
        avaliarSlider.setMajorTickSpacing(1);
        avaliarSlider.setMaximum(5);
        avaliarSlider.setMinimum(1);
        avaliarSlider.setPaintLabels(true);
        avaliarSlider.setPaintTicks(true);
        avaliarSlider.setSnapToTicks(true);
        avaliarSlider.setToolTipText("");
        jPanel1.add(avaliarSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 670, 560, 60));

        avaliacaoTxt.setText("Avaliação*:");
        jPanel1.add(avaliacaoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, -1, -1));

        comboTipo.setBackground(new java.awt.Color(250, 250, 250));
        comboTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboTipo.setMaximumRowCount(3);
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filme", "Série", "Livro" }));
        comboTipo.setToolTipText("");
        jPanel1.add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 220, 40));

        classificacaoTxt.setText("Classificação*:");
        jPanel1.add(classificacaoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 200, -1, -1));

        generoTxt.setText("Gênero*:");
        jPanel1.add(generoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, -1, -1));

        Fplataforma.setBackground(new java.awt.Color(250, 250, 250));
        Fplataforma.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(Fplataforma, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 530, 40));

        plataformaTxt.setText("Plataforma:");
        jPanel1.add(plataformaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, -1, -1));

        btn_cadastroMidia1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btn_cadastroMidia1.setText("Cadastrar Mídia");
        btn_cadastroMidia1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_cadastroMidia1.setContentAreaFilled(false);
        btn_cadastroMidia1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cadastroMidia1.setFocusable(false);
        btn_cadastroMidia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastroMidia1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cadastroMidia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 700, 250, 30));

        comboClassificacao.setBackground(new java.awt.Color(250, 250, 250));
        comboClassificacao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboClassificacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L", "10", "12", "14", "16", "18" }));
        comboClassificacao.setToolTipText("");
        jPanel1.add(comboClassificacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 220, 230, 40));

        Fcriador.setBackground(new java.awt.Color(250, 250, 250));
        Fcriador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(Fcriador, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 492, 530, 40));

        jLabel1.setText("Criador:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, -1, -1));

        btnGeneros.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnGeneros.setText("Generos:");
        btnGeneros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGeneros.setContentAreaFilled(false);
        btnGeneros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerosActionPerformed(evt);
            }
        });
        jPanel1.add(btnGeneros, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 410, 120, 40));

        Fgenero.setBackground(new java.awt.Color(250, 250, 250));
        Fgenero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Fgenero.setEnabled(false);
        jPanel1.add(Fgenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 400, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 790));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        FrameApp_home.trocaPanel("Perfil", new Perfil());
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_cadastroMidia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastroMidia1ActionPerformed
        String nome = this.Fnome.getText();
        String plataforma = this.Fplataforma.getText();
        //String genero = this.comboGenero.getSelectedItem().toString();
        String descricao = this.Fsobre.getText();
        String data = Fdata.getText();
        String criador = Fcriador.getText();
        Date dataLancamento = ConverteData(data);
        int tipo_midia = comboTipo.getSelectedIndex() + 1;
        int classificacao = comboClassificacao.getSelectedIndex() + 1;
        int avaliacao = avaliarSlider.getValue();
        int id_usuario = userSelecionado.getId();
        
        boolean ok = midiaControl.CadastraMidia(nome, descricao, plataforma,
                criador, dataLancamento, tipo_midia, classificacao, avaliacao,
                id_usuario);
        
        if(ok){
            System.out.println("certo");
        } else {
            System.err.println("erro");
        }
    }//GEN-LAST:event_btn_cadastroMidia1ActionPerformed

    private void btnGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerosActionPerformed
        FrameApp_lista janela = new FrameApp_lista(generosSelecionados);
        janela.setVisible(true);
    }//GEN-LAST:event_btnGenerosActionPerformed

    
    private Date ConverteData(String data){
        try{
        Date dataDate = null;
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        dataDate = format.parse(data);
        return dataDate;
        } catch (ParseException ex){
            return null;
        }
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Assistido;
    private javax.swing.JTextField Fcriador;
    private javax.swing.JFormattedTextField Fdata;
    private javax.swing.JTextField Fgenero;
    private javax.swing.JTextField Fnome;
    private javax.swing.JTextField Fplataforma;
    private javax.swing.JTextArea Fsobre;
    private javax.swing.JLabel avaliacaoTxt;
    private javax.swing.JSlider avaliarSlider;
    private javax.swing.JLabel backmidia;
    private javax.swing.JButton btnGeneros;
    private javax.swing.JButton btn_cadastroMidia1;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel classificacaoTxt;
    private javax.swing.JComboBox<String> comboClassificacao;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel dataTxt;
    private javax.swing.JLabel descricaoTxt;
    private javax.swing.JLabel generoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nomeTxt;
    private javax.swing.JLabel plataformaTxt;
    private javax.swing.JLabel tipoTxt;
    // End of variables declaration//GEN-END:variables
}
