/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.ImageIcon;

/**
 *
 * @author 0068961
 */
public class CadastroMidia extends javax.swing.JPanel {

    /**
     * Creates new form CadastroMidia
     */
    public CadastroMidia() {
        initComponents();
        config();
    }
    
    public void config(){
        ImageIcon imgLogo = new ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\resources\\backmidia.png");
        this.backmidia.setIcon(imgLogo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Assistido = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btn_cadastroMidia = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        backmidia = new javax.swing.JLabel();
        Fnome = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        nomeTxt = new javax.swing.JLabel();
        tipoTxt = new javax.swing.JLabel();
        Fdata = new javax.swing.JFormattedTextField();
        dataTxt = new javax.swing.JLabel();
        Fnao = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Fsobre = new javax.swing.JTextArea();
        descricaoTxt = new javax.swing.JLabel();
        avaliarSlider = new javax.swing.JSlider();
        avaliacaoTxt = new javax.swing.JLabel();
        Fsim = new javax.swing.JRadioButton();
        assistidoTxt = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        classificacaoTxt = new javax.swing.JLabel();
        Fgenero = new javax.swing.JTextField();
        generoTxt = new javax.swing.JLabel();
        Fplataforma = new javax.swing.JTextField();
        urlTxt = new javax.swing.JLabel();
        Furl = new javax.swing.JTextField();
        plataformaTxt = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1270, 788));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cadastroMidia.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btn_cadastroMidia.setText("Cadastrar Mídia");
        btn_cadastroMidia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_cadastroMidia.setContentAreaFilled(false);
        btn_cadastroMidia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cadastroMidia.setFocusable(false);
        btn_cadastroMidia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastroMidiaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cadastroMidia, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 710, 250, 30));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backmidia, javax.swing.GroupLayout.DEFAULT_SIZE, 1270, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backmidia, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 180));

        Fnome.setBackground(new java.awt.Color(250, 250, 250));
        Fnome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(Fnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 560, 40));

        jComboBox1.setBackground(new java.awt.Color(250, 250, 250));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L", "10", "12", "14", "16", "18" }));
        jComboBox1.setToolTipText("");
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 550, 110, 40));

        nomeTxt.setText("Nome*:");
        jPanel1.add(nomeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        tipoTxt.setText("Tipo*");
        jPanel1.add(tipoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, -1, -1));

        Fdata.setBackground(new java.awt.Color(250, 250, 250));
        try {
            Fdata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Fdata.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Fdata.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(Fdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 220, 260, 40));

        dataTxt.setText("Data de lançamento:");
        jPanel1.add(dataTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 200, -1, -1));

        Fnao.setBackground(new java.awt.Color(250, 250, 250));
        Assistido.add(Fnao);
        Fnao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Fnao.setText("Não");
        Fnao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Fnao.setFocusable(false);
        jPanel1.add(Fnao, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 560, 60, 30));

        Fsobre.setBackground(new java.awt.Color(250, 250, 250));
        Fsobre.setColumns(20);
        Fsobre.setRows(5);
        jScrollPane2.setViewportView(Fsobre);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 560, 320));

        descricaoTxt.setText("Descrição:");
        jPanel1.add(descricaoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        avaliarSlider.setBackground(new java.awt.Color(250, 250, 250));
        avaliarSlider.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        avaliarSlider.setForeground(new java.awt.Color(51, 51, 51));
        avaliarSlider.setMajorTickSpacing(1);
        avaliarSlider.setMaximum(5);
        avaliarSlider.setMinimum(1);
        avaliarSlider.setPaintLabels(true);
        avaliarSlider.setPaintTicks(true);
        avaliarSlider.setSnapToTicks(true);
        avaliarSlider.setToolTipText("");
        avaliarSlider.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(avaliarSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 680, 330, 60));

        avaliacaoTxt.setText("Avaliação*:");
        jPanel1.add(avaliacaoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 660, -1, -1));

        Fsim.setBackground(new java.awt.Color(250, 250, 250));
        Assistido.add(Fsim);
        Fsim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Fsim.setText("Sim");
        Fsim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Fsim.setFocusable(false);
        jPanel1.add(Fsim, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 560, 60, 30));

        assistidoTxt.setText("Assistido*:");
        jPanel1.add(assistidoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 530, -1, -1));

        comboTipo.setBackground(new java.awt.Color(250, 250, 250));
        comboTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboTipo.setMaximumRowCount(3);
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filme", "Série", "Livro" }));
        comboTipo.setToolTipText("");
        jPanel1.add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 210, 40));

        classificacaoTxt.setText("Classificação*:");
        jPanel1.add(classificacaoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, -1, -1));

        Fgenero.setBackground(new java.awt.Color(250, 250, 250));
        Fgenero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(Fgenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 530, 40));

        generoTxt.setText("Gênero:");
        jPanel1.add(generoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, -1, -1));

        Fplataforma.setBackground(new java.awt.Color(250, 250, 250));
        Fplataforma.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(Fplataforma, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 520, 40));

        urlTxt.setText("URL para foto:");
        jPanel1.add(urlTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        Furl.setBackground(new java.awt.Color(250, 250, 250));
        Furl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(Furl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 560, 40));

        plataformaTxt.setText("Plataforma:");
        jPanel1.add(plataformaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 790));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastroMidiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastroMidiaActionPerformed
        FrameApp_home.trocaPanel("CadastroMidia", new CadastroMidia());
    }//GEN-LAST:event_btn_cadastroMidiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Assistido;
    private javax.swing.JFormattedTextField Fdata;
    private javax.swing.JTextField Fgenero;
    private javax.swing.JRadioButton Fnao;
    private javax.swing.JTextField Fnome;
    private javax.swing.JTextField Fplataforma;
    private javax.swing.JRadioButton Fsim;
    private javax.swing.JTextArea Fsobre;
    private javax.swing.JTextField Furl;
    private javax.swing.JLabel assistidoTxt;
    private javax.swing.JLabel avaliacaoTxt;
    private javax.swing.JSlider avaliarSlider;
    private javax.swing.JLabel backmidia;
    private javax.swing.JButton btn_cadastroMidia;
    private javax.swing.JLabel classificacaoTxt;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel dataTxt;
    private javax.swing.JLabel descricaoTxt;
    private javax.swing.JLabel generoTxt;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nomeTxt;
    private javax.swing.JLabel plataformaTxt;
    private javax.swing.JLabel tipoTxt;
    private javax.swing.JLabel urlTxt;
    // End of variables declaration//GEN-END:variables
}
