/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author 0068961
 */
public class Cadastro extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bemvindoTxt = new javax.swing.JLabel();
        emailF = new javax.swing.JTextField();
        cadastrarBTN = new javax.swing.JButton();
        senhaF = new javax.swing.JPasswordField();
        senhaF1 = new javax.swing.JPasswordField();
        nomeF = new javax.swing.JTextField();
        membroTxt = new javax.swing.JLabel();
        acessarcontaTxt = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(398, 598));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        bemvindoTxt.setBackground(new java.awt.Color(102, 102, 102));
        bemvindoTxt.setFont(new java.awt.Font("Rubik", 0, 24)); // NOI18N
        bemvindoTxt.setForeground(new java.awt.Color(102, 102, 102));
        bemvindoTxt.setText("Criar Conta");

        emailF.setBackground(new java.awt.Color(230, 230, 230));
        emailF.setForeground(new java.awt.Color(51, 51, 51));
        emailF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailF.setBorder(null);
        emailF.setPreferredSize(new java.awt.Dimension(80, 80));

        cadastrarBTN.setBackground(new java.awt.Color(230, 230, 230));
        cadastrarBTN.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        cadastrarBTN.setForeground(new java.awt.Color(102, 102, 102));
        cadastrarBTN.setText("Cadastrar");
        cadastrarBTN.setBorder(null);
        cadastrarBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        senhaF.setBackground(new java.awt.Color(230, 230, 230));
        senhaF.setForeground(new java.awt.Color(51, 51, 51));
        senhaF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        senhaF.setBorder(null);
        senhaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaFActionPerformed(evt);
            }
        });

        senhaF1.setBackground(new java.awt.Color(230, 230, 230));
        senhaF1.setForeground(new java.awt.Color(51, 51, 51));
        senhaF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        senhaF1.setBorder(null);
        senhaF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaF1ActionPerformed(evt);
            }
        });

        nomeF.setBackground(new java.awt.Color(230, 230, 230));
        nomeF.setForeground(new java.awt.Color(51, 51, 51));
        nomeF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomeF.setBorder(null);
        nomeF.setPreferredSize(new java.awt.Dimension(80, 80));

        membroTxt.setBackground(new java.awt.Color(153, 153, 153));
        membroTxt.setForeground(new java.awt.Color(153, 153, 153));
        membroTxt.setText("Já é um membro?");

        acessarcontaTxt.setBackground(new java.awt.Color(51, 255, 51));
        acessarcontaTxt.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        acessarcontaTxt.setForeground(new java.awt.Color(51, 255, 51));
        acessarcontaTxt.setText("Acesse sua conta");
        acessarcontaTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acessarcontaTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acessarcontaTxtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(membroTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acessarcontaTxt))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nomeF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bemvindoTxt)
                        .addComponent(emailF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(senhaF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                            .addComponent(cadastrarBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(senhaF1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(bemvindoTxt)
                .addGap(48, 48, 48)
                .addComponent(nomeF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(emailF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(senhaF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(senhaF1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(cadastrarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(membroTxt)
                    .addComponent(acessarcontaTxt))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void senhaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaFActionPerformed

    private void senhaF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaF1ActionPerformed

    private void acessarcontaTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acessarcontaTxtMouseClicked
        FrameApp.trocaPainel("Login", new Login());
    }//GEN-LAST:event_acessarcontaTxtMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acessarcontaTxt;
    private javax.swing.JLabel bemvindoTxt;
    private javax.swing.JButton cadastrarBTN;
    private javax.swing.JTextField emailF;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel membroTxt;
    private javax.swing.JTextField nomeF;
    private javax.swing.JPasswordField senhaF;
    private javax.swing.JPasswordField senhaF1;
    // End of variables declaration//GEN-END:variables
}
