/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import control.UsuarioControl;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author 0068961
 */
public class Cadastro extends javax.swing.JPanel {

    private static UsuarioControl usuarioControl;

    public Cadastro() {
        initComponents();
        config();
        this.usuarioControl = new UsuarioControl();
    }

    public void config() {
        ImageIcon icon = new ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\resources\\logo_mini.png");
        ImageIcon bg = new ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\resources\\fundo_login.png");
        icon.setImage(icon.getImage().getScaledInstance(80, 80, 100));
        this.lblicon.setIcon(icon);
        this.lblFundo.setIcon(bg);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bemvindoTxt = new javax.swing.JLabel();
        emailF = new javax.swing.JTextField();
        cadastrarBTN = new javax.swing.JButton();
        senhaF = new javax.swing.JPasswordField();
        senhaF1 = new javax.swing.JPasswordField();
        nomeF = new javax.swing.JTextField();
        membroTxt = new javax.swing.JLabel();
        acessarcontaTxt = new javax.swing.JLabel();
        nomeTxt = new javax.swing.JLabel();
        emailTxt = new javax.swing.JLabel();
        senhaTxt = new javax.swing.JLabel();
        senha1Txt = new javax.swing.JLabel();
        lblicon = new javax.swing.JLabel();
        xTxt = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(398, 598));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bemvindoTxt.setBackground(new java.awt.Color(102, 102, 102));
        bemvindoTxt.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        bemvindoTxt.setForeground(new java.awt.Color(102, 102, 102));
        bemvindoTxt.setText("Criar Conta");
        jPanel2.add(bemvindoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        emailF.setBackground(new java.awt.Color(230, 230, 230));
        emailF.setForeground(new java.awt.Color(153, 153, 153));
        emailF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailF.setText("seuemail@gmail.com");
        emailF.setBorder(null);
        emailF.setPreferredSize(new java.awt.Dimension(80, 80));
        emailF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFFocusLost(evt);
            }
        });
        jPanel2.add(emailF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 340, 42));

        cadastrarBTN.setBackground(new java.awt.Color(230, 230, 230));
        cadastrarBTN.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        cadastrarBTN.setForeground(new java.awt.Color(0, 51, 0));
        cadastrarBTN.setText("Cadastrar");
        cadastrarBTN.setBorder(null);
        cadastrarBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrarBTN.setFocusable(false);
        cadastrarBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadastrarBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadastrarBTNMouseExited(evt);
            }
        });
        cadastrarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBTNActionPerformed(evt);
            }
        });
        jPanel2.add(cadastrarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 466, 340, 41));

        senhaF.setBackground(new java.awt.Color(230, 230, 230));
        senhaF.setForeground(new java.awt.Color(153, 153, 153));
        senhaF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        senhaF.setText("suasenha");
        senhaF.setBorder(null);
        senhaF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                senhaFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                senhaFFocusLost(evt);
            }
        });
        senhaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaFActionPerformed(evt);
            }
        });
        jPanel2.add(senhaF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 340, 42));
        senhaF.setEchoChar((char)0);

        senhaF1.setBackground(new java.awt.Color(230, 230, 230));
        senhaF1.setForeground(new java.awt.Color(153, 153, 153));
        senhaF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        senhaF1.setText("suasenha");
        senhaF1.setBorder(null);
        senhaF1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                senhaF1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                senhaF1FocusLost(evt);
            }
        });
        senhaF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaF1ActionPerformed(evt);
            }
        });
        jPanel2.add(senhaF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 340, 42));
        senhaF1.setEchoChar((char)0);

        nomeF.setBackground(new java.awt.Color(230, 230, 230));
        nomeF.setForeground(new java.awt.Color(153, 153, 153));
        nomeF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomeF.setText("seunome");
        nomeF.setBorder(null);
        nomeF.setPreferredSize(new java.awt.Dimension(80, 80));
        nomeF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeFFocusLost(evt);
            }
        });
        jPanel2.add(nomeF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 340, 42));

        membroTxt.setBackground(new java.awt.Color(153, 153, 153));
        membroTxt.setForeground(new java.awt.Color(153, 153, 153));
        membroTxt.setText("Já é um membro?");
        jPanel2.add(membroTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 519, -1, -1));

        acessarcontaTxt.setBackground(new java.awt.Color(51, 255, 51));
        acessarcontaTxt.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        acessarcontaTxt.setForeground(new java.awt.Color(51, 255, 51));
        acessarcontaTxt.setText("Acesse sua conta");
        acessarcontaTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acessarcontaTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acessarcontaTxtMouseClicked(evt);
            }
        });
        jPanel2.add(acessarcontaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, -1, -1));

        nomeTxt.setBackground(new java.awt.Color(153, 153, 153));
        nomeTxt.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        nomeTxt.setForeground(new java.awt.Color(153, 153, 153));
        nomeTxt.setText("Nome");
        jPanel2.add(nomeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        emailTxt.setBackground(new java.awt.Color(153, 153, 153));
        emailTxt.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        emailTxt.setForeground(new java.awt.Color(153, 153, 153));
        emailTxt.setText("Email");
        jPanel2.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        senhaTxt.setBackground(new java.awt.Color(153, 153, 153));
        senhaTxt.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        senhaTxt.setForeground(new java.awt.Color(153, 153, 153));
        senhaTxt.setText("Senha");
        jPanel2.add(senhaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        senha1Txt.setBackground(new java.awt.Color(153, 153, 153));
        senha1Txt.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        senha1Txt.setForeground(new java.awt.Color(153, 153, 153));
        senha1Txt.setText("Repita sua senha");
        jPanel2.add(senha1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));
        jPanel2.add(lblicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 80));

        xTxt.setBackground(new java.awt.Color(204, 204, 204));
        xTxt.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        xTxt.setForeground(new java.awt.Color(0, 51, 0));
        xTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xTxt.setText("X");
        xTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        xTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xTxtMouseExited(evt);
            }
        });
        jPanel2.add(xTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 30, 40));
        jPanel2.add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void senhaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaFActionPerformed

    private void senhaF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaF1ActionPerformed

    private void acessarcontaTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acessarcontaTxtMouseClicked
        FrameApp_Login.trocaPainel("Login", new Login());
    }//GEN-LAST:event_acessarcontaTxtMouseClicked

    private void nomeFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeFFocusGained
        if (this.nomeF.getText().equals("seunome")) {
            this.nomeF.setText("");
            this.nomeF.setForeground(new Color(51, 51, 51));
        }
    }//GEN-LAST:event_nomeFFocusGained

    private void nomeFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeFFocusLost
        if (this.nomeF.getText().equals("")) {
            this.nomeF.setText("seunome");
            this.nomeF.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_nomeFFocusLost

    private void emailFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFFocusGained
        if (this.emailF.getText().equals("seuemail@gmail.com")) {
            this.emailF.setText("");
            this.emailF.setForeground(new Color(51, 51, 51));
        }
    }//GEN-LAST:event_emailFFocusGained

    private void emailFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFFocusLost
        if (this.emailF.getText().equals("")) {
            this.emailF.setText("seuemail@gmail.com");
            this.emailF.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_emailFFocusLost

    private void senhaFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhaFFocusGained
        this.senhaF.setEchoChar('*');
        String password = String.valueOf(senhaF.getPassword());
        if (password.toLowerCase().equals("suasenha")) {
            this.senhaF.setText("");
            this.senhaF.setForeground(new Color(51, 51, 51));
        }
    }//GEN-LAST:event_senhaFFocusGained

    private void senhaFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhaFFocusLost
        String password = String.valueOf(senhaF.getPassword());
        if (password.equalsIgnoreCase("")) {
            this.senhaF.setEchoChar((char) 0);
            if (password.toLowerCase().equals("")) {
                this.senhaF.setText("suasenha");
                this.senhaF.setForeground(new Color(153, 153, 153));
            }
        }
    }//GEN-LAST:event_senhaFFocusLost

    private void senhaF1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhaF1FocusGained
        this.senhaF1.setEchoChar('*');
        String password = String.valueOf(senhaF1.getPassword());
        if (password.toLowerCase().equals("suasenha")) {
            this.senhaF1.setText("");
            this.senhaF1.setForeground(new Color(51, 51, 51));
        }
    }//GEN-LAST:event_senhaF1FocusGained

    private void senhaF1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhaF1FocusLost
        String password = String.valueOf(senhaF1.getPassword());
        if (password.equalsIgnoreCase("")) {
            this.senhaF1.setEchoChar((char) 0);
            if (password.toLowerCase().equals("")) {
                this.senhaF1.setText("suasenha");
                this.senhaF1.setForeground(new Color(153, 153, 153));
            }
        }
    }//GEN-LAST:event_senhaF1FocusLost

    private void cadastrarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBTNActionPerformed

        String nome = nomeF.getText();
        String email = emailF.getText();
        String senha = String.valueOf(senhaF.getPassword());

        boolean ok = this.usuarioControl.cadastraUsuario(nome, email, senha);

        if (ok == true) {
            JOptionPane.showMessageDialog(this, "Usuario cadastrado", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_cadastrarBTNActionPerformed

    private void xTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xTxtMouseEntered
        this.xTxt.setForeground(Color.white);
    }//GEN-LAST:event_xTxtMouseEntered

    private void xTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xTxtMouseExited
        this.xTxt.setForeground(new Color(0,51,0));
    }//GEN-LAST:event_xTxtMouseExited

    private void xTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xTxtMouseClicked
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        parentFrame.dispose();
    }//GEN-LAST:event_xTxtMouseClicked

    private void cadastrarBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarBTNMouseEntered
        this.cadastrarBTN.setForeground(Color.white);
    }//GEN-LAST:event_cadastrarBTNMouseEntered

    private void cadastrarBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarBTNMouseExited
        this.cadastrarBTN.setForeground(new Color(0,51,0));
    }//GEN-LAST:event_cadastrarBTNMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acessarcontaTxt;
    private javax.swing.JLabel bemvindoTxt;
    private javax.swing.JButton cadastrarBTN;
    private javax.swing.JTextField emailF;
    private javax.swing.JLabel emailTxt;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblicon;
    private javax.swing.JLabel membroTxt;
    private javax.swing.JTextField nomeF;
    private javax.swing.JLabel nomeTxt;
    private javax.swing.JLabel senha1Txt;
    private javax.swing.JPasswordField senhaF;
    private javax.swing.JPasswordField senhaF1;
    private javax.swing.JLabel senhaTxt;
    private javax.swing.JLabel xTxt;
    // End of variables declaration//GEN-END:variables
}
