/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import control.UsuarioControl;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import model.Usuario;

/**
 *
 * @author 0068961
 */
public class Login extends javax.swing.JPanel {

    private static UsuarioControl usuarioControl;

    public Login() {
        initComponents();
        config();
        this.usuarioControl = new UsuarioControl();
    }

    public void config() {
        ImageIcon icon = new ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\resources\\logo_mini.png");
        ImageIcon bg = new ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\resources\\fundo_login.png");
        icon.setImage(icon.getImage().getScaledInstance(80, 80, 100));
        this.lblicon.setIcon(icon);
        this.lblFundo.setIcon(bg);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bemvindoTxt = new javax.swing.JLabel();
        emailF = new javax.swing.JTextField();
        entrarBTN = new javax.swing.JButton();
        senhaF = new javax.swing.JPasswordField();
        membroTxt = new javax.swing.JLabel();
        cadastroTxt = new javax.swing.JLabel();
        emailTxt = new javax.swing.JLabel();
        senhaTxt = new javax.swing.JLabel();
        lblicon = new javax.swing.JLabel();
        xTxt = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(398, 598));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bemvindoTxt.setBackground(new java.awt.Color(102, 102, 102));
        bemvindoTxt.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        bemvindoTxt.setForeground(new java.awt.Color(102, 102, 102));
        bemvindoTxt.setText("Bem vindo");
        jPanel2.add(bemvindoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));
        bemvindoTxt.grabFocus();

        emailF.setBackground(new java.awt.Color(230, 230, 230));
        emailF.setForeground(new java.awt.Color(153, 153, 153));
        emailF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailF.setText("seuemail@gmail.com");
        emailF.setBorder(null);
        emailF.setPreferredSize(new java.awt.Dimension(80, 80));
        emailF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFFocusLost(evt);
            }
        });
        jPanel2.add(emailF, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 198, 340, 42));

        entrarBTN.setBackground(new java.awt.Color(230, 230, 230));
        entrarBTN.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        entrarBTN.setForeground(new java.awt.Color(0, 51, 0));
        entrarBTN.setText("Entrar");
        entrarBTN.setBorder(null);
        entrarBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entrarBTN.setFocusable(false);
        entrarBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrarBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entrarBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                entrarBTNMouseExited(evt);
            }
        });
        entrarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarBTNActionPerformed(evt);
            }
        });
        jPanel2.add(entrarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 422, 340, 41));

        senhaF.setBackground(new java.awt.Color(230, 230, 230));
        senhaF.setForeground(new java.awt.Color(153, 153, 153));
        senhaF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        senhaF.setText("suasenha");
        senhaF.setBorder(null);
        senhaF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                senhaFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                senhaFFocusLost(evt);
            }
        });
        senhaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaFActionPerformed(evt);
            }
        });
        jPanel2.add(senhaF, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 322, 340, 42));
        senhaF.setEchoChar((char)0);

        membroTxt.setBackground(new java.awt.Color(153, 153, 153));
        membroTxt.setForeground(new java.awt.Color(153, 153, 153));
        membroTxt.setText("Não é um membro?");
        jPanel2.add(membroTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 469, -1, -1));

        cadastroTxt.setBackground(new java.awt.Color(51, 255, 51));
        cadastroTxt.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        cadastroTxt.setForeground(new java.awt.Color(51, 255, 51));
        cadastroTxt.setText("Cadastre-se agora");
        cadastroTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastroTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastroTxtMouseClicked(evt);
            }
        });
        jPanel2.add(cadastroTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, -1, -1));

        emailTxt.setBackground(new java.awt.Color(153, 153, 153));
        emailTxt.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        emailTxt.setForeground(new java.awt.Color(153, 153, 153));
        emailTxt.setText("Email");
        jPanel2.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 176, -1, -1));

        senhaTxt.setBackground(new java.awt.Color(153, 153, 153));
        senhaTxt.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        senhaTxt.setForeground(new java.awt.Color(153, 153, 153));
        senhaTxt.setText("Senha");
        jPanel2.add(senhaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 300, -1, -1));
        jPanel2.add(lblicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 80));

        xTxt.setBackground(new java.awt.Color(204, 204, 204));
        xTxt.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        xTxt.setForeground(new java.awt.Color(0, 51, 0));
        xTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xTxt.setText("X");
        xTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        xTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xTxtMouseExited(evt);
            }
        });
        jPanel2.add(xTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 30, 40));
        jPanel2.add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void senhaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaFActionPerformed

    private void cadastroTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroTxtMouseClicked
        FrameApp_Login.trocaPainel("Cadastro", new Cadastro());
    }//GEN-LAST:event_cadastroTxtMouseClicked

    private void emailFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFFocusGained
        if (this.emailF.getText().equals("seuemail@gmail.com")) {
            this.emailF.setText("");
            this.emailF.setForeground(new Color(51, 51, 51));
        }
    }//GEN-LAST:event_emailFFocusGained

    private void emailFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFFocusLost
        if (this.emailF.getText().equals("")) {
            this.emailF.setText("seuemail@gmail.com");
            this.emailF.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_emailFFocusLost

    private void senhaFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhaFFocusGained
        this.senhaF.setEchoChar('*');
        String password = String.valueOf(senhaF.getPassword());
        if (password.toLowerCase().equals("suasenha")) {
            this.senhaF.setText("");
            this.senhaF.setForeground(new Color(51, 51, 51));
        }
    }//GEN-LAST:event_senhaFFocusGained

    private void senhaFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhaFFocusLost
        String password = String.valueOf(senhaF.getPassword());
        if (password.equalsIgnoreCase("")) {
            this.senhaF.setEchoChar((char) 0);
            if (password.toLowerCase().equals("")) {
                this.senhaF.setText("suasenha");
                this.senhaF.setForeground(new Color(153, 153, 153));
            }
        }
    }//GEN-LAST:event_senhaFFocusLost

    private void entrarBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarBTNMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_entrarBTNMouseClicked

    private void entrarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarBTNActionPerformed
        String email = emailF.getText();
        String senha = String.valueOf(senhaF.getPassword());
        boolean ok = this.usuarioControl.logaUsuario(email, senha);

        if (ok == true) {
            Usuario userLogado;
            userLogado = this.usuarioControl.getUsuario(email, senha);
            FrameApp_home janela = new FrameApp_home(userLogado);
            janela.setVisible(true);
            JFrame frameParent = (JFrame) SwingUtilities.getWindowAncestor(this);
            frameParent.dispose();

        } else {

        }
    }//GEN-LAST:event_entrarBTNActionPerformed

    private void xTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xTxtMouseEntered
        this.xTxt.setForeground(Color.white);
    }//GEN-LAST:event_xTxtMouseEntered

    private void xTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xTxtMouseExited
        this.xTxt.setForeground(new Color(0,51,0));
    }//GEN-LAST:event_xTxtMouseExited

    private void xTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xTxtMouseClicked
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        parentFrame.dispose();
    }//GEN-LAST:event_xTxtMouseClicked

    private void entrarBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarBTNMouseEntered
        this.entrarBTN.setForeground(Color.white);
    }//GEN-LAST:event_entrarBTNMouseEntered

    private void entrarBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarBTNMouseExited
        this.entrarBTN.setForeground(new Color(0,51,0));
    }//GEN-LAST:event_entrarBTNMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bemvindoTxt;
    private javax.swing.JLabel cadastroTxt;
    private javax.swing.JTextField emailF;
    private javax.swing.JLabel emailTxt;
    private javax.swing.JButton entrarBTN;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblicon;
    private javax.swing.JLabel membroTxt;
    private javax.swing.JPasswordField senhaF;
    private javax.swing.JLabel senhaTxt;
    private javax.swing.JLabel xTxt;
    // End of variables declaration//GEN-END:variables
}
