/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import model.Usuario;

/**
 *
 * @author 0068961
 */
public class Perfil extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Perfil() {
        initComponents();
    }

    public Perfil(Usuario userSelecionado) {
        initComponents();
        config(userSelecionado);
    }

    public void config(Usuario userSelecionado) {
        String nomeUsuario = userSelecionado.getNome();
        String primeiroNome = nomeUsuario.split(" ")[0];
        primeiroNome = primeiroNome.substring(0, 1).toUpperCase().concat(primeiroNome.substring(1));
        this.nomeTxt.setText(primeiroNome);
        ImageIcon profilePic = new ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\resources\\profile_pic.png");
        profilePic.setImage(profilePic.getImage().getScaledInstance(
                128, 128, 100));
        fotoUser.setText("");
        fotoUser.setIcon(profilePic);
        Fnome.setText(nomeUsuario);
    }

    /*
    ## METODO IMAGE PARA BYTES<
    private byte[] imgByte(File file) {
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        try {
            FileInputStream fis = new FileInputStream(file);

            byte[] buf = new byte[1024];
            for (int readNum; (readNum = fis.read(buf)) != -1;) {
                bos.write(buf, 0, readNum);
            }
        } catch (FileNotFoundException ex) {
            return null;
        } catch (IOException ex) {
            return null;
        }
        byte[] bytes = bos.toByteArray();
        return bytes;
    }>
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        fotoUser = new javax.swing.JLabel();
        fundo = new javax.swing.JPanel();
        nomeTxt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaMidia = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        midiaTxt = new javax.swing.JLabel();
        btn_verDetalhes = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtNome = new javax.swing.JLabel();
        Fnome = new javax.swing.JTextField();
        Fdata = new javax.swing.JFormattedTextField();
        txtData = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1270, 3000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(250, 250, 250));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fotoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fotoUser.setText("foto");
        fotoUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(fotoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 128, 128));

        fundo.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout fundoLayout = new javax.swing.GroupLayout(fundo);
        fundo.setLayout(fundoLayout);
        fundoLayout.setHorizontalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        fundoLayout.setVerticalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );

        jPanel3.add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, -1));

        nomeTxt.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        nomeTxt.setText("<NOME USUÁRIO>");
        jPanel3.add(nomeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        listaMidia.setBackground(new java.awt.Color(250, 250, 250));
        jScrollPane1.setViewportView(listaMidia);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 690, 420));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 10, 500));

        midiaTxt.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        midiaTxt.setText("Mídias Cadastradas");
        jPanel3.add(midiaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, -1, -1));

        btn_verDetalhes.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_verDetalhes.setText("Ver Detalhes");
        btn_verDetalhes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_verDetalhes.setContentAreaFilled(false);
        btn_verDetalhes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_verDetalhes.setFocusable(false);
        btn_verDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verDetalhesActionPerformed(evt);
            }
        });
        jPanel3.add(btn_verDetalhes, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 730, 190, 30));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 700, 10));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 530, 10));

        txtNome.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtNome.setText("Nome");
        jPanel3.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        Fnome.setBackground(new java.awt.Color(250, 250, 250));
        jPanel3.add(Fnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 500, -1));

        Fdata.setBackground(new java.awt.Color(250, 250, 250));
        try {
            Fdata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Fdata.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Fdata.setText("  /  /    ");
        jPanel3.add(Fdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 130, -1));

        txtData.setText("Data de nascimento");
        jPanel3.add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 790));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_verDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verDetalhesActionPerformed
        if (this.listaMidia.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma mídia!", "Seleção", JOptionPane.INFORMATION_MESSAGE);
        } else {

        }
    }//GEN-LAST:event_btn_verDetalhesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Fdata;
    private javax.swing.JTextField Fnome;
    private javax.swing.JButton btn_verDetalhes;
    private javax.swing.JLabel fotoUser;
    private javax.swing.JPanel fundo;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JList<String> listaMidia;
    private javax.swing.JLabel midiaTxt;
    private javax.swing.JLabel nomeTxt;
    private javax.swing.JLabel txtData;
    private javax.swing.JLabel txtNome;
    // End of variables declaration//GEN-END:variables
}
